server:
  port: 9999

spring:
  application:
    name: nacos-server-consumer #如果使用feign远程调用服务，不能使用下划线，类似hosts文件域名
  #配置nacos服务端地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#feign底层依赖ribbon实现负载均衡和远程调用
#配置ribbon的超时时间
ribbon:
  ConnectTimeout: 1000 #连接超时时间，默认1000ms
  ReadTimeout: 3000 #逻辑处理的连接时间，默认1000ms

#设置当前的日志级别，feign只支持debug级别的日志
logging:
  level:
    #缩小日志记录范围
    com.itheima: debug

# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true