server:
  port: 9999

spring:
  application:
    name: springcloud-config-eureka-server
eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000